In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'Text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'Output':[1,1,0,0]})

In [3]:
df

Text  Output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

/home/zahir/Tf_gpu/tfgpu1/lib/python3.12/site-packages/sklearn/utils/_param_validation.py:14: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 2.3.1)
  from scipy.sparse import csr_matrix, issparse


In [5]:
bow = cv.fit_transform(df['Text'])

In [6]:
# Vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [8]:
cv.transform(['campusx watch and write coment of campusx']).toarray()

array([[2, 0, 0, 1, 1]])