In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'Text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'Output':[1,1,0,0]})

In [3]:
df

Text  Output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [17]:
bow = cv.fit_transform(df['Text'])

In [18]:
# Vocabulary
print(cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [21]:
print(len(cv.vocabulary_))

4


In [22]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0]]
[[1 0 0 0]]


In [23]:
cv.transform(['campusx watch and write coment of campusx']).toarray()

array([[0, 0, 0, 0]])